### ISSUE TITLE
Tìm hiểu: Kiến trúc của Máy ảo Java (Java Architecture)

### ISSUE THREAD

**Issue by vinhdq842** [monthui0002/SE04-Nhom21.1#2]
Máy ảo Java bao gồm classloader, memory area, execution engine v.v.

Kiến trúc của Máy ảo Java
a) ClassLoader

ClassLoader là một hệ thống con được sử dụng để tải các class file. Nó thực hiện ba chức năng chính: Loading, Linking và Initialization (Khởi tạo)

b) Method Area

JVM Method Area lưu trữ các cấu trúc lớp (class) như: metadata, the constant runtime pool và code của các method.

c) Heap

Tất cả các Object, các biến đối tượng liên quan và mảng (Array) của chúng được lưu trữ trong heap. Bộ nhớ này là phổ biến và được chia sẻ trên nhiều luồng.

4) JVM languae Stacks

JVM languae Stacks lưu trữ các biến cục bộ (local variables) và một phần kết quả của nó. Mỗi luồng có JVM stack riêng, được tạo đồng thời khi luồng được tạo.

Một khung mới được tạo bất cứ khi nào một phương thức được gọi và nó sẽ bị xóa khi quá trình gọi phương thức hoàn tất.

5) PC Register

PC Register lưu trữ địa chỉ của hướng dẫn máy ảo Java hiện đang thực thi. Trong Java, mỗi luồng có thanh ghi PC riêng biệt.

6) Native Method Stacks

Native Method Stacks giữ hướng dẫn của mã gốc phụ thuộc vào thư viện riêng. Nó được viết bằng ngôn ngữ khác thay vì Java.

7) Execution Engine

Execution Engine là một loại phần mềm được sử dụng để kiểm tra phần cứng, phần mềm hoặc hệ thống hoàn chỉnh.

Công cụ thực hiện kiểm tra không bao giờ mang bất kỳ thông tin nào về sản phẩm được kiểm tra.

8) Native Method interface

Native Method interface là một Famework. Nó cho phép mã Java đang chạy trong JVM được gọi bởi các thư viện và ứng dụng gốc.

Native Libraries là một tập hợp các thư viện riêng (C, C ++) cần thiết cho Execution Engine (công cụ thực thi).

**Comment by monthui0002** [comment]
![sodo](https://user-images.githubusercontent.com/48514468/103476889-15e6cd00-4dec-11eb-8aff-824917c683a9.png)

**Comment by nvhuy1509** [comment]
Mình tìm hiểu được là Máy ảo java gồm 3 thành phần chính này, Mọi người xem rồi cho ý kiến nhé. 
- Class Loader: Tìm kiếm và load các file *.class vào vùng nhớ của java dưới dạng bytecode
- Data Area : vùng nhớ hệ thống cấp phát cho Java Virtual Machine
- Execution Engine: chuyển các lệnh của JVM trong file *.class thành các lệnh của máy, hệ điều hành tương ứng và thực thi chúng.

**Comment by vinhdq842** [comment]
> Mình tìm hiểu được là Máy ảo java gồm 3 thành phần chính này, Mọi người xem rồi cho ý kiến nhé.
> 
> * Class Loader: Tìm kiếm và load các file *.class vào vùng nhớ của java dưới dạng bytecode
> * Data Area : vùng nhớ hệ thống cấp phát cho Java Virtual Machine
> * Execution Engine: chuyển các lệnh của JVM trong file *.class thành các lệnh của máy, hệ điều hành tương ứng và thực thi chúng.

Cảm ơn góp ý của bạn.
