### ISSUE TITLE
Quá trình thực thi và biên dịch mã phần mềm

### ISSUE THREAD

**Issue by vinhdq842** [monthui0002/SE04-Nhom21.1#3]

**Comment by khaicochinh** [comment]
Theo mình biết thì quá trình biên dịch mã phần mềm gồm:
- Chương trình nguồn được đưa vào trình biên dịch, sau đó trình biên dịch sẽ biên dịch ra chương trình đích
![image](https://user-images.githubusercontent.com/67938514/103480150-235c8100-4e05-11eb-96ae-24a5027b00de.png)

**Comment by monthui0002** [comment]
**Quá trình thực thi và biên dịch mã phần mềm theo tôi thì gồm các phần sau:**

**Editor** - Để nhập chương trình của bạn vào và trình biên dịch, hiện nay có rất nhiều công cụ như notepad, Intellij, ....

**Compiler** - Để chuyển đổi chương trình ngôn ngữ cao của bạn thành mã máy gốc

**Linker** - Để kết hợp các tệp chương trình khác nhau trong chương trình chính của bạn với nhau.

**Loader** - Để tải các tệp từ thiết bị lưu trữ thứ cấp của bạn như Đĩa cứng, Flash Drive, CD vào RAM để thực thi. Việc tải được tự động thực hiện khi bạn thực thi mã của mình.

**Execution** - Thực thi mã được xử lý bởi hệ điều hành & bộ xử lý của bạn.

**Comment by nvhuy1509** [comment]
- Trình biên dịch sẽ biên dịch ba tệp và tạo ra 3 tệp .class tương ứng chứa BYTE code. Không giống như C, không có liên kết được thực hiện.
- JVM hoặc Máy ảo Java nằm trên RAM. Trong quá trình thực thi, sử dụng class loader, class files được đưa vào RAM. Tại đây BYTE code được xác minh cho tính bảo mật.
- Tiếp theo, Execution Engine sẽ chuyển đổi bytecode thành mã máy gốc. Đây chỉ là trong thời gian biên dịch. Đây là một trong những lý do chính tại sao Java tương đối chậm.

**Comment by vinhdq842** [comment]
Mã nguồn Java (.java) sẽ được biên dịch ra mã bytecode, sau đó qua một quá trình preverify rồi thu được các file *.class. JVM sẽ tiến hành thông dịch các mã bytecode này và thực thi chúng.  Để hiểu thêm về bytecode các bạn có thể dùng phần mềm Java Bytecode Editor (JBE) mở các file class để xem cấu trúc.
![image](https://user-images.githubusercontent.com/44129600/103481381-3c693000-4e0d-11eb-8455-6465d64104ed.png)
Ngày xưa mình có nghiên cứu các opcodes của Java nhằm mục đích sửa mã của file class, khá vui.
![image](https://user-images.githubusercontent.com/44129600/103481427-8e11ba80-4e0d-11eb-91ec-5d8897cad33b.png)
