### ISSUE TITLE
Biên dịch và thực thi mã Java trong Java VM

### ISSUE THREAD

**Issue by vinhdq842** [monthui0002/SE04-Nhom21.1#4]
Tìm hiểu cách biên dịch và thực thi mã Java trong JVM

**Comment by monthui0002** [comment]
**Biên dịch và thực thi**
Ví dụ, bạn có 1 hàm main với 2 phương thức f1 và f2
phương thức main **(main.java), f1 (f1.java), f2(f2.java)**
**Compiler**(Trình biên dịch) sẽ biên dịch 3 file trên thành **main.class, f1.class** và **f2.class** tương ứng chứa các đoạn bytecode. Tức là không có liên kết nào được thực hiện giữa 3 file này.

**Class Loader** sẽ đưa các file trên vào RAM(vì máy ảo JVM nằm trên RAM), tại đây byte code được xác minh tính bảo mật

**Execution Engine** chuyển đổi các mã bytecode này thành mã máy (điều này có nghĩa là việc thực hiện chuyển đổi này thực hiện vào thời điểm mã chạy) là một lý do khiến **Java** tương đối chậm so với **C**

**Comment by nvhuy1509** [comment]
Ồ. Mình hiểu rồi ~~

**Comment by vinhdq842** [comment]
> **Biên dịch và thực thi**
> Ví dụ, bạn có 1 hàm main với 2 phương thức f1 và f2
> phương thức main **(main.java), f1 (f1.java), f2(f2.java)**
> **Compiler**(Trình biên dịch) sẽ biên dịch 3 file trên thành **main.class, f1.class** và **f2.class** tương ứng chứa các đoạn bytecode. Tức là không có liên kết nào được thực hiện giữa 3 file này.
> 
> **Class Loader** sẽ đưa các file trên vào RAM(vì máy ảo JVM nằm trên RAM), tại đây byte code được xác minh tính bảo mật
> 
> **Execution Engine** chuyển đổi các mã bytecode này thành mã máy (điều này có nghĩa là việc thực hiện chuyển đổi này thực hiện vào thời điểm mã chạy) là một lý do khiến **Java** tương đối chậm so với **C**

Bổ sung:
- Java là một ngôn ngữ hướng đối tượng, class-based.
-  Một chương trình Java đơn giản được bắt đầu từ hàm tĩnh main, ta có thể chạy thử đoạn code mẫu sau:
`
public class Main{
     public static void main(String[] args){
          System.out.println("Hello, World!");
     }
}
`
- lưu đoạn code trên vào file Main.java rồi mở commandline gõ lệnh sau để chạy:
`
 javac Main.java
java Main
`
