### ISSUE TITLE
Viết báo cáo thu hoạch cuối kì

### ISSUE THREAD

**Issue by vinhdq842** [monthui0002/SE04-Nhom21.1#8]

**Comment by khaicochinh** [comment]
Hậu viết báo cáo thu hoạch cuối kì nhé anh em

**Comment by vinhdq842** [comment]
> Hậu viết báo cáo thu hoạch cuối kì nhé anh em

Hiện tôi đã viết xong file README.md nhé, ae hoàn thành nốt 1 file pdf nữa để trình chiếu.

**Comment by monthui0002** [comment]
file PDF done lâu rồi nhé :((
